Repository jfrog/artifactory-client-java, pull requests merged in 2023-11, with the labels that each got.

#370 Support $match and $nmatch in AqlQueryBuilder
  services/src/main/java/org/jfrog/artifactory/client/aql/AqlItem.java
  services/src/main/java/org/jfrog/artifactory/client/aql/AqlQueryBuilder.java
  services/src/test/java/org/jfrog/artifactory/client/aql/AqlQueryBuilderTest.java
Labels: improvement

#371 Support limit and offset in AqlQueryBuilder
  services/src/main/java/org/jfrog/artifactory/client/aql/AqlQueryBuilder.java
  services/src/test/java/org/jfrog/artifactory/client/aql/AqlQueryBuilderTest.java
Labels: improvement

#380 Add support for Terraform package type #354
  api/src/main/java/org/jfrog/artifactory/client/model/repository/settings/TerraformRepositorySettings.java
  services/src/main/java/org/jfrog/artifactory/client/impl/jackson/RepositorySettingsMixIn.java
  services/src/main/java/org/jfrog/artifactory/client/model/impl/FederatedRepositoryBuilderImpl.java
  services/src/main/java/org/jfrog/artifactory/client/model/impl/LocalRepositoryBuilderImpl.java
  services/src/main/java/org/jfrog/artifactory/client/model/impl/PackageTypeImpl.java
  services/src/main/java/org/jfrog/artifactory/client/model/impl/RemoteRepositoryBuilderImpl.java
  services/src/main/java/org/jfrog/artifactory/client/model/impl/VirtualRepositoryBuilderImpl.java
  services/src/main/java/org/jfrog/artifactory/client/model/repository/settings/impl/TerraformRepositorySettingsImpl.java
  services/src/test/groovy/org/jfrog/artifactory/client/BaseRepositoryTests.groovy
  services/src/test/groovy/org/jfrog/artifactory/client/TerraformPackageTypeRepositoryTests.groovy
Labels: new feature

#384 Update test dependencies
  httpClient/build.gradle
  httpClient/src/test/java/httpClient/HttpBuilderTest.java
  services/build.gradle
  services/src/main/resources/artifactory.client.release.properties
Labels: ignore for release
